services:
  server:
    build:
      dockerfile: ./Dockerfile
    container_name: usav3_server
    ports:
      - 25565:25565
      - 24454:24454/udp
    volumes: 
      - "server_storage:/server"

volumes:
  server_storage: